apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2hnu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2hnu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2hnu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2hnu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2hnu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mswt-tenant/rhtap-demo-app/hacbs-test-project-2hnu@sha256:56dc865db5dc8813ae9e0f186ef26291d415416ca5918d8205be73f51cd231ba
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
